"""Initial migration

Revision ID: 16e40bcae119
Revises: 
Create Date: 2026-09-16 16:28:08.116888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e40bcae119'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('financial_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('linked_event_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('is_salary', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('flexibility', sa.String(), nullable=True),
    sa.Column('minimum_allowed_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_financial_events_user_id'), 'financial_events', ['user_id'], unique=False)
    op.create_table('financial_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('home_currency', sa.String(), nullable=True),
    sa.Column('current_available_balance', sa.Float(), nullable=True),
    sa.Column('minimum_balance_to_keep', sa.Float(), nullable=True),
    sa.Column('financial_priorities', sa.JSON(), nullable=True),
    sa.Column('expense_categories_to_protect', sa.JSON(), nullable=True),
    sa.Column('expense_categories_willing_to_reduce', sa.JSON(), nullable=True),
    sa.Column('expense_categories_willing_to_stop', sa.JSON(), nullable=True),
    sa.Column('payment_methods_user_will_consider', sa.JSON(), nullable=True),
    sa.Column('max_installment_months', sa.Integer(), nullable=True),
    sa.Column('recurring_incomes', sa.JSON(), nullable=True),
    sa.Column('recurring_expenses', sa.JSON(), nullable=True),
    sa.Column('obligations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('scenarios',
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('base_decision_id', sa.String(), nullable=True),
    sa.Column('overrides', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_index(op.f('ix_scenarios_user_id'), 'scenarios', ['user_id'], unique=False)
    op.create_table('decisions',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('plans', sa.JSON(), nullable=True),
    sa.Column('evidence_metadata', sa.JSON(), nullable=True),
    sa.Column('scenario_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.scenario_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_decisions_request_id'), 'decisions', ['request_id'], unique=False)
    op.create_index(op.f('ix_decisions_user_id'), 'decisions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_user_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_request_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_scenarios_user_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_table('financial_profiles')
    op.drop_index(op.f('ix_financial_events_user_id'), table_name='financial_events')
    op.drop_table('financial_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
